name: Try Env Stuff
on:
  push:
    branches:
      - master
jobs:
  try-env-stuff:
    name: Try Env Stuff
    runs-on: ubuntu-latest
    steps:
      - id: save
        run: echo "::set-output name=build-name::foof"
      - env:
          BUILD_NAME: ${{ steps.save.outputs.build-name }}
        run: echo $BUILD_NAME

