name: Try Env Stuff
on:
  push:
    branches:
      - master
jobs:
  try-env-stuff:
    name: Try Env Stuff
    runs-on: ubuntu-latest
    steps:
      - env:
          GIT_REF: ${{ env.GITHUB_REF }}
        run: echo $GIT_REF

