name: "Release Please Build"

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Release Please
        uses: google-github-actions/release-please-action@v3.2.4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: Scratch

      - name: Checkout Code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
